// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasla;

#nullable disable

namespace Wasla.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703150754_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wasla.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.client@example.com",
                            MerchantId = 1,
                            Name = "Ahmed Client"
                        },
                        new
                        {
                            Id = 2,
                            Email = "layla.client@example.com",
                            MerchantId = 2,
                            Name = "Layla Client"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hassan.client@example.com",
                            MerchantId = 3,
                            Name = "Hassan Client"
                        });
                });

            modelBuilder.Entity("Wasla.Models.ClientPhones", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ClientId");

                    b.ToTable("ClientPhones");
                });

            modelBuilder.Entity("Wasla.Models.CompanyPhones", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyPhones");
                });

            modelBuilder.Entity("Wasla.Models.CourierCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Courier Company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "info@wasla.com",
                            CompanyName = "Wasla Express",
                            Password = "pass123"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "hello@fastship.com",
                            CompanyName = "FastShip",
                            Password = "secret"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "contact@citycouriers.com",
                            CompanyName = "CityCouriers",
                            Password = "pwd123"
                        });
                });

            modelBuilder.Entity("Wasla.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Email = "ziad@example.com",
                            Name = "Ziad Ahmed",
                            Password = "drv1"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Email = "omar@example.com",
                            Name = "Omar Khalid",
                            Password = "drv2"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            Email = "sara@example.com",
                            Name = "Sara Ali",
                            Password = "drv3"
                        });
                });

            modelBuilder.Entity("Wasla.Models.DriverOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("isActive")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Driver-Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DriverId = 1,
                            OrderId = 1,
                            isActive = "Active"
                        },
                        new
                        {
                            Id = 2,
                            DriverId = 2,
                            OrderId = 2,
                            isActive = "Active"
                        },
                        new
                        {
                            Id = 3,
                            DriverId = 3,
                            OrderId = 3,
                            isActive = "Active"
                        });
                });

            modelBuilder.Entity("Wasla.Models.DriverPhones", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("DriverId");

                    b.ToTable("DriverPhones");
                });

            modelBuilder.Entity("Wasla.Models.DriverVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Driver-Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2026, 6, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            ReturnedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2026, 6, 26, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 2,
                            ReturnedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 3,
                            ReturnedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("Wasla.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WalletBalance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Merchants", t =>
                        {
                            t.HasCheckConstraint("CK_Product_WalletBalance_NonNegative", "[WalletBalance] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alfa@store.com",
                            Name = "Alfa Store",
                            Password = "m1npass",
                            StoreName = "Alfa Store",
                            WalletBalance = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Email = "beta@shop.com",
                            Name = "Beta Shop",
                            Password = "m2npass",
                            StoreName = "Beta Shop",
                            WalletBalance = 250m
                        },
                        new
                        {
                            Id = 3,
                            Email = "gamma@market.com",
                            Name = "Gamma Market",
                            Password = "m3npass",
                            StoreName = "Gamma Market",
                            WalletBalance = 500m
                        });
                });

            modelBuilder.Entity("Wasla.Models.MerchantPhones", b =>
                {
                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MerchantId");

                    b.ToTable("MerchantPhones");
                });

            modelBuilder.Entity("Wasla.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityFrom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CityTo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TrackingUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isBreakable")
                        .HasColumnType("bit");

                    b.Property<bool>("isClaimingRequired")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.HasIndex("MerchantId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_TotalPrice", "TotalPrice >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityFrom = "Cairo",
                            CityTo = "Giza",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerAddress = "Cairo",
                            CustomerName = "Mohamed Ali",
                            CustomerPhone = "01001234567",
                            DeliveredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            MerchantId = 1,
                            PaymentType = "COD",
                            TotalPrice = 120m,
                            TrackingUuid = "TRK1001",
                            UpdatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            isBreakable = false,
                            isClaimingRequired = false
                        },
                        new
                        {
                            Id = 2,
                            CityFrom = "Giza",
                            CityTo = "Cairo",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerAddress = "Giza",
                            CustomerName = "Nora Hussein",
                            CustomerPhone = "01007654321",
                            DeliveredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            MerchantId = 2,
                            PaymentType = "Online",
                            TotalPrice = 80m,
                            TrackingUuid = "TRK1002",
                            UpdatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            isBreakable = true,
                            isClaimingRequired = false
                        },
                        new
                        {
                            Id = 3,
                            CityFrom = "Cairo",
                            CityTo = "Alexandria",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerAddress = "Alexandria",
                            CustomerName = "Omar Said",
                            CustomerPhone = "01009998877",
                            DeliveredAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverId = 1,
                            MerchantId = 3,
                            PaymentType = "COD",
                            TotalPrice = 200m,
                            TrackingUuid = "TRK1003",
                            UpdatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            isBreakable = false,
                            isClaimingRequired = true
                        });
                });

            modelBuilder.Entity("Wasla.Models.OrderCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AcceptanceState")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("OrderCompany", t =>
                        {
                            t.HasCheckConstraint("CK_OrderCompany_ShippingFee_NonNegative", "[ShippingFee] >= 0");
                        });
                });

            modelBuilder.Entity("Wasla.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Order-Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderProduct_Price", "Price >= 0");

                            t.HasCheckConstraint("CK_OrderProduct_Quantity", "QTY >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Item A",
                            OrderId = 1,
                            Price = 50m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Item B",
                            OrderId = 2,
                            Price = 35m,
                            Qty = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Item C",
                            OrderId = 3,
                            Price = 200m,
                            Qty = 1
                        });
                });

            modelBuilder.Entity("Wasla.Models.RateCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraKiloPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<double>("MinWeight")
                        .HasColumnType("float");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Rate Cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_RateCard_BaseFee_NonNegative", "[BaseFee] >= 0");

                            t.HasCheckConstraint("CK_RateCard_EffectiveDate_ExpiryDate", "[EffectiveDate] < [ExpiryDate]");

                            t.HasCheckConstraint("CK_RateCard_MaxWeight_NonNegative", "[MaxWeight] >= 0");

                            t.HasCheckConstraint("CK_RateCard_MinWeight_MaxWeight", "[MinWeight] < [MaxWeight]");

                            t.HasCheckConstraint("CK_RateCard_MinWeight_NonNegative", "[MinWeight] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseFee = 50m,
                            CompanyId = 1,
                            DestinationCity = "Giza",
                            EffectiveDate = new DateTime(2026, 6, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExtraKiloPrice = 10m,
                            MaxWeight = 5.0,
                            MinWeight = 0.0,
                            OriginCity = "Cairo"
                        },
                        new
                        {
                            Id = 2,
                            BaseFee = 80m,
                            CompanyId = 2,
                            DestinationCity = "Cairo",
                            EffectiveDate = new DateTime(2026, 6, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2027, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExtraKiloPrice = 8m,
                            MaxWeight = 10.0,
                            MinWeight = 0.0,
                            OriginCity = "Giza"
                        },
                        new
                        {
                            Id = 3,
                            BaseFee = 150m,
                            CompanyId = 1,
                            DestinationCity = "Alexandria",
                            EffectiveDate = new DateTime(2026, 6, 26, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpiryDate = new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ExtraKiloPrice = 12m,
                            MaxWeight = 20.0,
                            MinWeight = 0.0,
                            OriginCity = "Cairo"
                        });
                });

            modelBuilder.Entity("Wasla.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("RatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Stars")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MerchantId");

                    b.ToTable("Ratings", t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Score_Range", "[Stars] >= 1 AND [Stars] <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Good service",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 6, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MerchantId = 1,
                            RatedBy = "merchant",
                            Stars = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Excellent",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MerchantId = 2,
                            RatedBy = "merchant",
                            Stars = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Average",
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            MerchantId = 3,
                            RatedBy = "merchant",
                            Stars = 3.5
                        });
                });

            modelBuilder.Entity("Wasla.Models.TrackingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Tracking Histories of Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Merchant",
                            OrderId = 1,
                            Status = "ReadyForPickup",
                            Timestamp = new DateTime(2026, 6, 29, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Location = "Warehouse",
                            OrderId = 2,
                            Status = "Packed",
                            Timestamp = new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Location = "System",
                            OrderId = 3,
                            Status = "Created",
                            Timestamp = new DateTime(2026, 7, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Wasla.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DriverId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500.0,
                            CompanyId = 1,
                            DriverId = 1,
                            IsActive = "Active",
                            LicensePlate = "ABC-123",
                            Type = "Car"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 50.0,
                            CompanyId = 2,
                            DriverId = 1,
                            IsActive = "Active",
                            LicensePlate = "XYZ-987",
                            Type = "Motorcycle"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1200.0,
                            CompanyId = 1,
                            DriverId = 1,
                            IsActive = "Active",
                            LicensePlate = "LMN-456",
                            Type = "Van"
                        });
                });

            modelBuilder.Entity("Wasla.Models.Client", b =>
                {
                    b.HasOne("Wasla.Models.Merchant", "Merchant")
                        .WithMany("Clients")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Wasla.Models.ClientPhones", b =>
                {
                    b.HasOne("Wasla.Models.Client", "Client")
                        .WithMany("Phones")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Wasla.Models.CompanyPhones", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("Phones")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Wasla.Models.Driver", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Wasla.Models.DriverOrder", b =>
                {
                    b.HasOne("Wasla.Models.Driver", "Driver")
                        .WithMany("DriverOrders")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Order", "Order")
                        .WithOne("DriverOrder")
                        .HasForeignKey("Wasla.Models.DriverOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wasla.Models.DriverPhones", b =>
                {
                    b.HasOne("Wasla.Models.Driver", "Driver")
                        .WithMany("Phones")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Wasla.Models.DriverVehicle", b =>
                {
                    b.HasOne("Wasla.Models.Driver", "Driver")
                        .WithMany("DriverVehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Vehicle", "Vehicle")
                        .WithMany("DriverVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Wasla.Models.MerchantPhones", b =>
                {
                    b.HasOne("Wasla.Models.Merchant", "Merchant")
                        .WithMany("Phones")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Wasla.Models.Order", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("Orders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Driver", "Driver")
                        .WithMany("Orders")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Merchant", "Merchant")
                        .WithMany("Orders")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Driver");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Wasla.Models.OrderCompany", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("OrderCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Order", "order")
                        .WithOne("orderCompany")
                        .HasForeignKey("Wasla.Models.OrderCompany", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("order");
                });

            modelBuilder.Entity("Wasla.Models.OrderProduct", b =>
                {
                    b.HasOne("Wasla.Models.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wasla.Models.RateCard", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("RateCards")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Wasla.Models.Rating", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("Ratings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Merchant", "Merchant")
                        .WithMany("Ratings")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("Wasla.Models.TrackingHistory", b =>
                {
                    b.HasOne("Wasla.Models.Order", "Order")
                        .WithMany("TrackingHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wasla.Models.Vehicle", b =>
                {
                    b.HasOne("Wasla.Models.CourierCompany", "Company")
                        .WithMany("Vehicles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Wasla.Models.Client", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Wasla.Models.CourierCompany", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("OrderCompanies");

                    b.Navigation("Orders");

                    b.Navigation("Phones");

                    b.Navigation("RateCards");

                    b.Navigation("Ratings");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Wasla.Models.Driver", b =>
                {
                    b.Navigation("DriverOrders");

                    b.Navigation("DriverVehicles");

                    b.Navigation("Orders");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("Wasla.Models.Merchant", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Orders");

                    b.Navigation("Phones");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Wasla.Models.Order", b =>
                {
                    b.Navigation("DriverOrder")
                        .IsRequired();

                    b.Navigation("OrderProducts");

                    b.Navigation("TrackingHistories");

                    b.Navigation("orderCompany")
                        .IsRequired();
                });

            modelBuilder.Entity("Wasla.Models.Vehicle", b =>
                {
                    b.Navigation("DriverVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
